### ISSUE TITLE
Exception substring not found applying checker 

### ISSUE THREAD

**Issue by mo718** [puppet-meteor/MINER#1]
Hello,when I tried MINER, it reported the errors:
`ERROR: Restler engine failed. See logs in /home/zero/MINER/restler_bin_atten/project-server-test/FuzzLean directory for more information.`
the EngineStdErr.txt is empty,the EngineStdOut.txt is:
![image](https://user-images.githubusercontent.com/64512529/225318947-7e5f8018-798a-4493-82d1-73aea27c4ccd.png)
the engine_settings.json is:
{
  "per_resource_settings": {},
  "max_combinations": 20
}

**Comment by puppet-meteor** [comment]
Hi, it seems your experimental environment does not meet the requirements of RESTler. While I'm not sure of the specific reason. Maybe you are not using python3.8? Please follow the guidance of RESTler carefully (https://github.com/microsoft/restler-fuzzer).

**Comment by mo718** [comment]
The Restler can work normally in my experimental environment. My environment is Ubuntu20.04, python3.8.10, .net6.0 ,this is some errors:
![image](https://user-images.githubusercontent.com/64512529/225505131-97e32bdc-146e-478e-b866-6b7ba8087624.png)

**Comment by puppet-meteor** [comment]
Oh! I wrote several absolute paths in my code, so you can put it in this path '/home/MINER' as I mentioned in README. While I  haven't tried fuzz-lean for a long time, you may just try the fuzz command as shown in README. 
![image](https://user-images.githubusercontent.com/17903718/225510143-621b6345-46a7-4b26-9416-825ab5625926.png)

**Comment by mo718** [comment]
I put the code in /home/MINER,but it still error,like:
```
starttime: 2023-03-16 00:52:58.875597
Initializing: Garbage collection every 30 seconds.

 type: <class 'engine.core.sequences.Sequence'>
what seq: ['/projects']
what len: 2

 type: <class 'engine.core.sequences.Sequence'>
what seq: ['/projects', '/projects']
what len: 3
Exception substring not found applying checker <checkers.payload_body_checker.PayloadBodyChecker object at 0x7fd5e8f9f640>
Terminating garbage collection. Waiting for max 300 seconds.
finish run
substring not found
```
![image](https://user-images.githubusercontent.com/64512529/225552093-20904495-3571-4638-bab0-3baec6e0cedd.png)

**Comment by puppet-meteor** [comment]
https://github.com/microsoft/restler-fuzzer/issues/621
According to this issue, maybe disable PayloadBodyChecker and then have a try?
Our code is based on an older version of RESTler,  and RESTler has been patched since then. 
It's really hard to judge problems only by viewing logs, you can upload the related documents, and then we can test locally.

**Comment by mo718** [comment]
Thanks,I disabled the payloadbodyChecker, and it can work.
