### ISSUE TITLE
How to properly configure and use authentication tokens

### ISSUE THREAD

**Issue by PIAy3R** [puppet-meteor/MINER#10]
I followed the guide of Restler to add a token for authentication in MINER. I configured the `engine_settings.json` file as follows:
~~~
{
  "per_resource_settings": {},
  "max_combinations": 20,
  "authentication": {
    "token": {
      "location": "token.txt",
      "token_refresh_interval":  300
    }
 },
  "no_tokens_in_logs": false
}
~~~
In this configuration, the token is expected to be stored in a file named `token.txt`. Here's an example of how the token.txt file looks like:
~~~
{u'api': {}}
Authorization: Bearer 5796defa170a0bd8d847ee91d116131ff3ff2014d58dfcbaee86dbc416b440b1
~~~
and the fuzzing command is
~~~
/home/MINER/restler_bin_atten/restler/Restler fuzz --grammar_file ./Compile/grammar.py --dictionary_file ./Compile/dict.json --settings ./Compile/engine_settings.json --no_ssl --time_budget 1 --disable_checkers payloadbody
~~~
However, this setup did not work as expected.

I also attempted another approach by using a Python script (`token.py`) to generate the token dynamically. Here's the content of the `token.py` file:
~~~
import sys
import json

def main(argv=None):
    sys.stdout.write("{u'api': {}}\n")
    sys.stdout.write("Authorization: Bearer 5796defa170a0bd8d847ee91d116131ff3ff2014d58dfcbaee86dbc416b440b1\n")

if __name__ == "__main__":
    sys.exit(main())
~~~
I then modified the command to include the `token_refresh_command` option:
~~~
/home/MINER/restler_bin_atten/restler/Restler fuzz --grammar_file ./Compile/grammar.py --dictionary_file ./Compile/dict.json --settings ./Compile/engine_settings.json --no_ssl --time_budget 1 --disable_checkers payloadbody --token_refresh_command 'python token.py' --token_refresh_interval 720
~~~
Even with this method, MINER still failed to authenticate properly.

Additionally, I tried adding the token directly into the dictionary file (`dict.json`) using the `restler_custom_payload_header`option:
~~~
"restler_custom_payload_header": {
    "Authorization": 
    ["Bearer 5796defa170a0bd8d847ee91d116131ff3ff2014d58dfcbaee86dbc416b440b1"]
  }
~~~
However, none of these approaches resolved the authentication issue, there would always be a 401 status code in the responses of the requests I had sent.

I have verified that the file paths are correct.

**Comment by puppet-meteor** [comment]
Not sure the reason. 
In our experiments we also added the authentication tokens in requests and then passed the check.

**Comment by m0ck1ng** [comment]
It is weird. We have never met this before.
Another solution is to add your authentication tokens directly to the request grammar, like objects in `Compile/grammar.py`. 🤔
