### ISSUE TITLE
Error Question

### ISSUE THREAD

**Issue by painsAgains** [puppet-meteor/MINER#11]
Hi！
I see that the paper mentions that the 7 logic errors found by MINER have been confirmed by the developers. I was wondering if the logic errors regarding Gitlab were submitted to the Gitlab community? If it was submitted to the official community, can I see the URL?
Looking forward to your reply

**Comment by puppet-meteor** [comment]
The MINER work was finished years ago. It may be different to find the URL of the bugs. 
We submitted the discovered issues to the Gitlab git's issues. Some of the issues have been labeled as bug by the community, while others match known bug issues.

**Comment by painsAgains** [comment]
> The MINER work was finished years ago. It may be different to find the URL of the bugs. We submitted the discovered issues to the Gitlab git's issues. Some of the issues have been labeled as bug by the community, while others match known bug issues.

Where can I find these issues that have been marked as bugs by gitlab please? Can you tell me the URL of these issues? There are too many issues and I can't find the relevant ones.
Thank you very much!

**Comment by m0ck1ng** [comment]
Hi, here are some of our reports.
- https://gitlab.com/gitlab-org/gitlab/-/issues/339606
- https://gitlab.com/gitlab-org/gitlab/-/issues/344280
- https://gitlab.com/gitlab-org/gitlab/-/issues/344283
- https://gitlab.com/gitlab-org/gitlab/-/issues/346559
- https://gitlab.com/gitlab-org/gitlab/-/issues/346560
- https://gitlab.com/gitlab-org/gitlab/-/issues/344281

You can find more on the gitlab issue website.

**Comment by painsAgains** [comment]
Thanks a lot!

**Comment by m0ck1ng** [comment]
Please let us know if you find any more issues. Are we good to close this one?

**Comment by painsAgains** [comment]
Sure! You can colse this issue. Thank you again
