### ISSUE TITLE
Question about No.13 Error in Table 3 in the Paper 

### ISSUE THREAD

**Issue by critizero** [puppet-meteor/MINER#2]
![image](https://github.com/puppet-meteor/MINER/assets/37907345/c5340ef0-7502-422d-a475-ac45bab178e6)
The No.13 error is shown above. My question is that how can this error be found? In the useafterfree checker, it seems only check the sequence ends with delete, and try to add only one request after the sequence. So I think that this checker cannot generate a sequence with four requests in this case.
If this bug was not found by useafterfree checker, how can this sequence be found without response in 50x range?(In Fuzzing Module, it said that MINER stores sequence with response in 50x Range)
Thank you for your reply.

**Comment by m0ck1ng** [comment]
Hi, thanks for reaching out! The error was found by the UAF checker.

The UAF checker detects potential errors by reusing the resource that gets freed.  In this case,  the checker first frees the branch ```Br``` with the request ```DELETE /project/:id/repository/branches/:Br```. Then it adds a request ```POST /projects/:id/repository/branches``` to verify the accessibility of ```Br```. As the branch is created successfully, the checker confirms the accessibility of the deleted resource and reports a bug.  It should be noted that the raw request sequences could be complex and the majority of them have more than six requests, which can be found in fig. 6 in the paper. To illustrate the bug in a more comprehensive way,  we present a simplified version with core requests and add the request ```GET /projects/:id/repository/:Br``` to help understand.

**Comment by m0ck1ng** [comment]
Please let us know if you find any more issues. Are we good to close this one?

**Comment by critizero** [comment]
Thank you for your reply :)
