### ISSUE TITLE
MINER startup problem

### ISSUE THREAD

**Issue by Xiaoym23** [puppet-meteor/MINER#3]
Hello, I was wondering if MINER can run in Windows environment? The Restler in the home\MINER\restler_bin_atten\restler directory cannot be executed in Windows because it does not have a suffix. And I didn't find a file similar to build-restler.py in the RESTler repository(https://github.com/microsoft/restler-fuzzer), excuse me what method can let the MINER to run under Windows environment?

**Comment by puppet-meteor** [comment]
Sorry, there is no plan to adapt the Windows version of MINER in the near future.
