### ISSUE TITLE
Running MINER on WSL

### ISSUE THREAD

**Issue by himawanbayu** [puppet-meteor/MINER#4]
I tried to run MINER on Ubuntu (WSL) but I found this error. Can I use MINER on WSL?
![Screenshot 2023-10-20 082620](https://github.com/puppet-meteor/MINER/assets/37429713/345b4d7d-a3d3-44d8-b818-46003cfa8936)

**Comment by puppet-meteor** [comment]
First of all, as we introduced in README, our code must be placed under the '/home/MINER' path, because we set the absolute path in our code. 
Secondly, you may need to use `sudo su` to enter root mode and then run the command.

**Comment by himawanbayu** [comment]
I created the new one under '/home/MINER' but I still can't run 'Restler' to generate grammar. I used swagger.json from Restler, and put it in '/home/demo-test'. Do I need to create my own swagger?
![image](https://github.com/puppet-meteor/MINER/assets/37429713/7c79b8ce-7351-4759-abb1-4ad8fcb82666)

**Comment by puppet-meteor** [comment]
It has been a long time since we completed the experiment of Miner, and many experimental details have been forgotten. In my impression, RESTler's grammar generation function is not easy to use. We seem to mainly construct grammars manually.
