### ISSUE TITLE
how to generate Openapi specs for gitlab？

### ISSUE THREAD

**Issue by lixingquzhi** [puppet-meteor/MINER#5]
Or are there any resources available for me to download the openapi format specs for Gitlab?

**Comment by lixingquzhi** [comment]
When I tried to use 'rake gitlab:openapi:generate' in GitLab, I encountered the following error:
rake aborted!
LoadError: cannot load such file -- sigdump/setup

How did you resolve it?

**Comment by puppet-meteor** [comment]
It has been a long time since we completed the experiment of Miner, and many experimental details have been forgotten. In my impression, RESTler's grammar generation function is not easy to use. We seem to mainly construct grammars manually.

**Comment by lixingquzhi** [comment]
Thanks
