### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by yyyrf** [puppet-meteor/MINER#6]
Hello, I ran it according to the description in your readme, but after running it in the '/home/MINIER' path, I still reminded me that command not found. May I ask if it is possible to run it directly in the '/home/MINIER' path after pulling the project and loading requirement.txt? Do I need any additional configuration? Looking forward to your reply, I would greatly appreciate it.

**Comment by m0ck1ng** [comment]
It should directly work if you install the necessary dependencies (e.g., .NET 6.0) following [RESTLer's docs](https://github.com/microsoft/restler-fuzzer)🤔. And absolute paths are required for commands. 
May I have a look at your commands?

**Comment by yyyrf** [comment]
Thank you for your reply. I have already configured the environment related to Restler. I tried to switch to the root user and execute the command to test the blog sample in Restler, but the prompt was that I cannot find this command.
![2023-11-23 06-23-14屏幕截图](https://github.com/puppet-meteor/MINER/assets/151620464/acd64c3c-a7ba-42a3-9e13-ff81846d5853)

**Comment by puppet-meteor** [comment]
Since you have already accessed root privileges with "sudo su", there is no need to prepend "sudo" before the command. However, the screenshot indicates insufficient permissions. This may be due to a command line error or a problem with the provided grammar file.

**Comment by m0ck1ng** [comment]
There is something wrong with privileges. You should grant execution privileges (`+x`) with executable files like `Restler`.

**Comment by m0ck1ng** [comment]
Please let us know if you find any more issues. Are we good to close this one?

**Comment by yyyrf** [comment]
> Please let us know if you find any more issues. Are we good to close this one?

Thank you for your reply. I am very sorry for my delayed response. I have been busy with other things these past few days and have not been able to further run it. As you mentioned, I did not grant permission to run this binary program. The current issue should be just an environmental issue. The running environment of this program is NET5 or NET6, I'm here Running it in the NET6 environment prompts me that the version is too high and I need to downgrade to version 5?

**Comment by m0ck1ng** [comment]
Thanks for reaching out! We deployed MINER in an environment with .NET 5.0.202🤗. It could be possible that .NET 6 cannot apply to MINER🤔.

**Comment by m0ck1ng** [comment]
The issue has been resolved.

**Comment by yyyrf** [comment]
> The issue has been resolved.

thank you
