### ISSUE TITLE
fuzz error

### ISSUE THREAD

**Issue by iamhyyhy** [puppet-meteor/MINER#7]
Hello, after configuring the environment as required, I encountered the following error during the fuzz step. Can you help answer this question. 
![image](https://github.com/puppet-meteor/MINER/assets/152081486/a2b99cac-4932-4d15-92ac-efaeca4bbd04)

![image](https://github.com/puppet-meteor/MINER/assets/152081486/5412eaa2-7305-4435-b550-5590727b0674)

**Comment by m0ck1ng** [comment]
It seems that there is something wrong with your environment. Is python3 installed and available in cmd?
