### ISSUE TITLE
dict

### ISSUE THREAD

**Issue by yyyrf** [puppet-meteor/MINER#9]
Hello, I tested the Restler sample and blog example using MINER. During the process, I encountered a problem where I directly compiled its Swagger and then used MINER for fuzzing. The result was that only the GET API/docs executed successfully, while the rest failed. After modifying the dict.json file, I added a new int value to it, so that the rest of the APIs could execute successfully. However, when I used Restler to execute, But without modifying dict.json, all APIs can be successfully executed. What is the reason for this.

**Comment by puppet-meteor** [comment]
Hi, MINER is constructed based on RESTler with old version, so maybe nowadays RESTler has updated its Swagger compilation function.

**Comment by yyyrf** [comment]
Thank you very much for your reply. I have another question. After the testing is completed, the result given by the CMD interface is Request coverage (successful/total): 4/6. However, I have checked the network.testing file and the response result shows that all APIs have been executed. shouldn't this result be 6/6?

**Comment by m0ck1ng** [comment]
Hi, we built MINER on top of RESTler and inherited the ResultAnalyzer from RESTler.😥

We suggest you to re-check the response results or directly raise an issue to RESTler.🤔

**Comment by m0ck1ng** [comment]
Please let us know if you find any more issues. Are we good to close this one?

**Comment by yyyrf** [comment]
No problem, you can close it. Thank you.
